### ISSUE TITLE
Roadmap to > 1.1

### ISSUE THREAD

**Issue by grych** [grych/drab#104]
To be done after 1.0.0:

* [ ] optimistic updates with Drab.Element API
* [ ] render user templates in compile-time
* [ ] compress Drab JS templates
