### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by grych** [grych/drab#84]
Crude roadmap to 1.0. May change!

Features:
* [ ] commander/handler test framework
* [ ] unify API (bang functions)
* [ ] optimistic updates with Drab.Element API (elixirscript in a future)
* [ ] work with CI
* [ ] unit tests for JS
* [ ] compress Drab JS templates
* [ ] render user templates in compile-time
* [ ] Drab.Live cache compiled in module instead of DETS file
* [ ] unify shared and standard commander
* [ ] integration tests for broadcasting functions

Hard depreciations:
* [ ] Drab.Controller
* [ ] Drab.Client.js()
* [ ] Drab.run_handler()
* [ ] events handler declaration long form (drab-event & drab-handler)
* [ ] Drab.Browser.console!/2
* [ ] Drab.Browser.redirect_to!/2
